# Generated by Django 4.2.1 on 2025-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event',), name='unique_alert_per_event'),
        ),
    ]
